apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app
  labels:
    app: news-app
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: news-app
  template:
    metadata:
      labels:
        app: news-app
    spec:
      containers:
      - name: news-app
        image: 192.168.100.35:30541/news-app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: news-app-service
spec:
  selector:
    app: news-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort