const langData = {
    zh: {
        logoText: "全球新闻",
        settingsTitle: "设置",
        themeSetting: "主题",
        lightTheme: "浅色",
        darkTheme: "暗色",
        blueTheme: "蓝色",
        fontSizeSetting: "字体大小",
        smallFont: "小",
        mediumFont: "中",
        largeFont: "大",
        layoutSetting: "布局",
        listLayout: "列表",
        gridLayout: "网格",
        cardLayout: "卡片",
        autoRefresh: "自动刷新",
        refreshInterval: "刷新间隔",
        minutes: "分钟",
        previous: "上一页",
        next: "下一页",
        aboutUs: "关于我们",
        aboutText: "全球新闻为您提供最新、最全面的新闻报道",
        quickLinks: "快速链接",
        contact: "联系我们",
        privacy: "隐私政策",
        contactUs: "联系我们",
        login: "登录",
        logout: "退出",
        register: "注册",
        username: "用户名",
        password: "密码",
        confirmPassword: "确认密码",
        email: "邮箱",
        allRightsReserved: "版权所有",
        readMore: "查看详情",
        hot: "热门",
        searchPlaceholder: "搜索新闻...",
        usernamePlaceholder: "请输入用户名",
        passwordPlaceholder: "请输入密码",
        emailPlaceholder: "请输入邮箱",
        confirmPasswordPlaceholder: "请再次输入密码",
        forgotPassword: "忘记密码?",
        resetPassword: "重置密码",
        backToLogin: "返回登录",
        alreadyHaveAccount: "已有账号?",
        loginHere: "点击登录",
        likes: "点赞",
        share: "分享",
        comments: "评论",
        commentPlaceholder: "请输入您的评论...",
        submitComment: "提交评论",
        loginToComment: "请登录后发表评论",
        reply: "回复",
        replyPlaceholder: "请输入您的回复...",
        submit: "提交",
        cancel: "取消",
        backToList: "返回列表",
        relatedNews: "相关新闻",
        logout: '退出登录',
        profile: '个人资料',
        confirmLogout: '确定要退出登录吗？',
        loginRequired: '请输入用户名和密码',
        registerRequired: '请填写所有必填字段',
        passwordsNotMatch: '两次输入的密码不一致',
        newsData: [
            {
                id: 1,
                title: "国家主席发表重要讲话强调经济发展",
                description: "国家主席在近日的重要会议上发表讲话，强调要坚持稳中求进工作总基调，推动经济高质量发展。",
                content: "<p>国家主席在会议上指出，当前我国经济发展面临新的挑战和机遇。要坚持稳中求进工作总基调，完整、准确、全面贯彻新发展理念，加快构建新发展格局，着力推动高质量发展。</p><p>会议还讨论了其他重要议题，包括科技创新、民生保障和生态文明建设等。</p>",
                category: "domestic",
                date: "2023-05-15T10:00:00Z",
                source: "新华社",
                image: "https://picsum.photos/600/400?random=1",
                url: "https://www.xinhuanet.com/politics/2023-05/15/c_1129634567.htm",
                tags: ["latest", "hot", "politics", "economy"],
                likes: 42,
                views: 1024,
                comments: 35
            },
            {
                id: 2,
                title: "科技创新助力产业升级",
                description: "最新数据显示，我国在人工智能、5G等领域的创新成果显著，为产业升级提供了强大动力。",
                content: "<p>根据工业和信息化部发布的最新数据，我国在人工智能、5G通信、量子计算等前沿技术领域取得重大突破。</p><p>这些创新成果正在加速传统产业数字化转型，推动制造业向智能化、绿色化方向发展。</p>",
                category: "technology",
                date: "2023-05-14T14:30:00Z",
                source: "人民日报",
                image: "https://picsum.photos/600/400?random=2",
                url: "https://people.com.cn/n1/2023/0514/c1001-32698765.html",
                tags: ["latest", "economy"],
                likes: 28,
                views: 856,
                comments: 12
            },
            {
                id: 3,
                title: "国际社会高度评价中国外交政策",
                description: "多位国际专家表示，中国的外交政策为世界和平与发展作出了重要贡献。",
                content: "<p>在近日举行的国际论坛上，来自各国的专家学者对中国的外交政策给予了高度评价。专家们认为，中国提出的全球发展倡议和全球安全倡议为应对全球性挑战提供了中国方案。</p><p>中国坚持和平发展道路，积极参与全球治理体系改革，为世界和平与发展作出了重要贡献。</p>",
                category: "international",
                date: "2023-05-13T09:15:00Z",
                source: "央视新闻",
                image: "https://picsum.photos/600/400?random=3",
                url: "https://news.cctv.com/2023/05/13/ARTI123456789.shtml",
                tags: ["politics"],
                likes: 15,
                views: 723,
                comments: 8
            },
            {
                id: 4,
                title: "全国足球联赛精彩对决",
                description: "在昨晚进行的全国足球联赛中，两支劲旅上演了精彩对决，最终以2:2握手言和。",
                content: "<p>在昨晚进行的全国足球超级联赛第10轮比赛中，卫冕冠军与联赛领头羊上演了一场精彩对决。双方在上半场各进一球，下半场又各入一球，最终以2:2的比分握手言和。</p><p>这场比赛吸引了超过5万名观众到场观看，创下了本赛季上座率新高。</p>",
                category: "sports",
                date: "2023-05-12T20:45:00Z",
                source: "新浪体育",
                image: "https://picsum.photos/600/400?random=4",
                url: "https://sports.sina.com.cn/china/j/2023-05-12/doc-im123456789.shtml",
                tags: ["hot"],
                likes: 56,
                views: 1542,
                comments: 42
            },
            {
                id: 5,
                title: "新电影《时代之光》首映获好评",
                description: "由著名导演执导的新片《时代之光》昨日首映，观众和影评人一致给予高度评价。",
                content: "<p>由著名导演张艺谋执导的新片《时代之光》昨日在北京举行全球首映礼。影片通过三个不同时代的故事，展现了中国社会的变迁和发展。</p><p>首映结束后，观众和影评人对影片给予了高度评价，认为这是一部兼具艺术性和思想性的佳作。</p>",
                category: "entertainment",
                date: "2023-05-11T18:00:00Z",
                source: "腾讯娱乐",
                image: "https://picsum.photos/600/400?random=5",
                url: "https://ent.qq.com/a/20230511/123456.htm",
                tags: ["latest"],
                likes: 37,
                views: 932,
                comments: 21
            },
            {
                id: 6,
                title: "健康生活方式讲座受欢迎",
                description: "市卫生健康委员会举办的健康生活方式系列讲座受到市民热烈欢迎，场场爆满。",
                content: "<p>由市卫生健康委员会主办的'健康中国·健康城市'系列讲座近日在全市各社区举行。讲座内容涵盖合理膳食、科学运动、心理健康等多个方面。</p><p>据主办方介绍，每场讲座都吸引了大量市民参与，不少场次甚至出现'一座难求'的情况。</p>",
                category: "domestic",
                date: "2023-05-10T15:20:00Z",
                source: "地方日报",
                image: "https://picsum.photos/600/400?random=6",
                url: "https://www.localdaily.com.cn/news/2023-05-10/123456.html",
                tags: ["health"],
                likes: 19,
                views: 645,
                comments: 5
            },
            {
                id: 7,
                title: "新能源汽车销量再创新高",
                description: "4月份我国新能源汽车销量同比增长超过120%，市场渗透率达到25%。",
                content: "<p>根据中国汽车工业协会发布的数据，4月份我国新能源汽车产销分别完成31.2万辆和29.9万辆，同比均增长超过120%。</p><p>新能源汽车市场渗透率达到25%，意味着每销售4辆新车中就有1辆是新能源汽车。</p>",
                category: "technology",
                date: "2023-05-09T11:30:00Z",
                source: "经济日报",
                image: "https://picsum.photos/600/400?random=7",
                url: "https://www.jingjiribao.cn/html/2023-05/09/content_123456.htm",
                tags: ["economy", "latest"],
                likes: 31,
                views: 876,
                comments: 18
            },
            {
                id: 8,
                title: "国际货币基金组织上调中国经济增长预期",
                description: "IMF将2023年中国经济增长预期上调至5.2%，认为中国经济复苏势头强劲。",
                content: "<p>国际货币基金组织(IMF)在最新发布的《世界经济展望报告》中，将2023年中国经济增长预期上调0.8个百分点至5.2%。</p><p>IMF认为，中国优化调整防疫政策后，经济复苏势头强劲，消费和服务业快速恢复，将为全球经济增长作出重要贡献。</p>",
                category: "international",
                date: "2023-05-08T16:45:00Z",
                source: "金融时报",
                image: "https://picsum.photos/600/400?random=8",
                url: "https://www.financialtimes.com/content/123456789",
                tags: ["economy", "politics"],
                likes: 24,
                views: 765,
                comments: 9
            }
        ]
    },
    en: {
        logoText: "Global News",
        settingsTitle: "Settings",
        themeSetting: "Theme",
        lightTheme: "Light",
        darkTheme: "Dark",
        blueTheme: "Blue",
        fontSizeSetting: "Font Size",
        smallFont: "Small",
        mediumFont: "Medium",
        largeFont: "Large",
        layoutSetting: "Layout",
        listLayout: "List",
        gridLayout: "Grid",
        cardLayout: "Card",
        autoRefresh: "Auto Refresh",
        refreshInterval: "Refresh Interval",
        minutes: "Minutes",
        previous: "Previous",
        next: "Next",
        aboutUs: "About Us",
        aboutText: "Global News provides you with the latest and most comprehensive news coverage",
        quickLinks: "Quick Links",
        contact: "Contact",
        privacy: "Privacy Policy",
        contactUs: "Contact Us",
        login: "Login",
        logout: "Logout",
        register: "Register",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        email: "Email",
        allRightsReserved: "All Rights Reserved",
        readMore: "Read More",
        hot: "Hot",
        searchPlaceholder: "Search news...",
        usernamePlaceholder: "Enter username",
        passwordPlaceholder: "Enter password",
        emailPlaceholder: "Enter email",
        confirmPasswordPlaceholder: "Confirm password",
        forgotPassword: "Forgot Password?",
        resetPassword: "Reset Password",
        backToLogin: "Back to Login",
        alreadyHaveAccount: "Already have an account?",
        loginHere: "Login here",
        likes: "Likes",
        share: "Share",
        comments: "Comments",
        commentPlaceholder: "Enter your comment...",
        submitComment: "Submit Comment",
        loginToComment: "Please login to comment",
        reply: "Reply",
        replyPlaceholder: "Enter your reply...",
        submit: "Submit",
        cancel: "Cancel",
        backToList: "Back to List",
        relatedNews: "Related News",
        logout: 'Logout',
        profile: 'Profile',
        confirmLogout: 'Are you sure you want to logout?',
        loginRequired: 'Please enter username and password',
        registerRequired: 'Please fill all required fields',
        passwordsNotMatch: 'Passwords do not match',
        newsData: [
            {
                id: 1,
                title: "President delivers important speech emphasizing economic development",
                description: "The President delivered a speech at an important meeting recently, emphasizing the need to maintain stability while pursuing progress and promoting high-quality economic development.",
                content: "<p>In his speech, the President pointed out that China's economic development is facing new challenges and opportunities. It is necessary to adhere to the general principle of pursuing progress while ensuring stability, fully and faithfully implement the new development philosophy, accelerate the establishment of a new development paradigm, and focus on promoting high-quality development.</p><p>The meeting also discussed other important topics, including technological innovation, people's livelihood, and ecological civilization construction.</p>",
                category: "domestic",
                date: "2023-05-15T10:00:00Z",
                source: "Xinhua News",
                image: "https://picsum.photos/600/400?random=1",
                url: "https://www.xinhuanet.com/english/2023-05/15/c_1310712345.htm",
                tags: ["latest", "hot", "politics", "economy"],
                likes: 42,
                views: 1024,
                comments: 35
            },
            {
                id: 2,
                title: "Technological innovation drives industrial upgrading",
                description: "Latest data shows significant achievements in AI, 5G and other fields, providing strong momentum for industrial upgrading.",
                content: "<p>According to the latest data released by the Ministry of Industry and Information Technology, China has made major breakthroughs in cutting-edge technologies such as artificial intelligence, 5G communications, and quantum computing.</p><p>These innovations are accelerating the digital transformation of traditional industries and promoting the development of manufacturing towards intelligence and green development.</p>",
                category: "technology",
                date: "2023-05-14T14:30:00Z",
                source: "People's Daily",
                image: "https://picsum.photos/600/400?random=2",
                url: "https://en.people.cn/n3/2023/0514/c90000-20012345.html",
                tags: ["latest", "economy"],
                likes: 28,
                views: 856,
                comments: 12
            },
            {
                id: 3,
                title: "International community praises China's foreign policy",
                description: "International experts say China's foreign policy has made important contributions to world peace and development.",
                content: "<p>At a recent international forum, experts and scholars from various countries spoke highly of China's foreign policy. Experts believe that the Global Development Initiative and Global Security Initiative proposed by China provide Chinese solutions to global challenges.</p><p>China adheres to the path of peaceful development, actively participates in the reform of the global governance system, and has made important contributions to world peace and development.</p>",
                category: "international",
                date: "2023-05-13T09:15:00Z",
                source: "CCTV News",
                image: "https://picsum.photos/600/400?random=3",
                url: "https://english.cctv.com/2023/05/13/ARTI123456789.shtml",
                tags: ["politics"],
                likes: 15,
                views: 723,
                comments: 8
            },
            {
                id: 4,
                title: "Thrilling match in national football league",
                description: "Two strong teams played a thrilling match in the national football league last night, ending in a 2-2 draw.",
                content: "<p>In the 10th round of the Chinese Football Association Super League last night, the defending champion and the league leader played a thrilling match. Both teams scored one goal in the first half and another in the second half, ending the game with a 2-2 draw.</p><p>The match attracted over 50,000 spectators, setting a new attendance record for this season.</p>",
                category: "sports",
                date: "2023-05-12T20:45:00Z",
                source: "Sina Sports",
                image: "https://picsum.photos/600/400?random=4",
                url: "https://sports.sina.com.cn/global/2023-05-12/doc-im123456789.shtml",
                tags: ["hot"],
                likes: 56,
                views: 1542,
                comments: 42
            },
            {
                id: 5,
                title: "New film 'Light of the Era' receives acclaim at premiere",
                description: "The new film 'Light of the Era' directed by renowned director Zhang Yimou premiered yesterday to high praise from audiences and critics.",
                content: "<p>The new film 'Light of the Era', directed by renowned director Zhang Yimou, held its global premiere in Beijing yesterday. Through stories from three different eras, the film showcases the changes and development of Chinese society.</p><p>After the premiere, audiences and critics praised the film highly, considering it an excellent work combining artistry and ideological depth.</p>",
                category: "entertainment",
                date: "2023-05-11T18:00:00Z",
                source: "Tencent Entertainment",
                image: "https://picsum.photos/600/400?random=5",
                url: "https://www.yahoo.com/entertainment/zhang-yimou-new-film-premiere-123456789.html",
                tags: ["latest"],
                likes: 37,
                views: 932,
                comments: 21
            },
            {
                
                id: 6,
                title: "Healthy lifestyle lectures attract large crowds",
                description: "A series of lectures on healthy lifestyles organized by the municipal health commission have been warmly welcomed by citizens, with every session fully booked.",
                content: "<p>A series of lectures titled 'Healthy China, Healthy City' organized by the municipal health commission were recently held in communities across the city. The lectures covered various aspects including balanced diet, scientific exercise, and mental health.</p><p>According to the organizers, each lecture attracted a large number of citizens, with many sessions being fully booked.</p>",
                category: "domestic",
                date: "2023-05-10T15:20:00Z",
                source: "Local Daily",
                image: "https://picsum.photos/600/400?random=6",
                url: "https://www.localdaily.com.cn/news/2023-05-10/123456.html",
                tags: ["health"],
                likes: 19,
                views: 645,
                comments: 5
            },
            {
                id: 7,
                title: "New energy vehicle sales reach new heights",
                description: "In April, new energy vehicle sales in China grew by over 120% year-on-year, with a market penetration rate of 25%.",
                content: "<p>According to data released by the China Association of Automobile Manufacturers, in April, new energy vehicle production and sales in China reached 312,000 and 299,000 units respectively, both growing by over 120% year-on-year.</p><p>The market penetration rate of new energy vehicles reached 25%, meaning that one in every four new vehicles sold is a new energy vehicle.</p>",
                category: "technology",
                date: "2023-05-09T11:30:00Z",
                source: "Economic Daily",
                image: "https://picsum.photos/600/400?random=7",
                url: "https://www.jingjiribao.cn/html/2023-05/09/content_123456.htm",
                tags: ["economy", "latest"],
                likes: 31,
                views: 876,
                comments: 18
            },
            {
                id: 8,
                title: "IMF raises China's economic growth forecast",
                description: "The International Monetary Fund (IMF) has raised its 2023 economic growth forecast for China to 5.2%, citing a strong economic recovery.",
                content: "<p>The International Monetary Fund (IMF) in its latest World Economic Outlook report has raised China's 2023 economic growth forecast by 0.8 percentage points to 5.2%.</p><p>IMF believes that after China optimized its epidemic prevention policy, the economic recovery is strong, with rapid recovery in consumption and services, contributing significantly to global economic growth.</p>",
                category: "international",
                date: "2023-05-08T16:45:00Z",
                source: "Financial Times",
                image: "https://picsum.photos/600/400?random=8",
                url: "https://www.financialtimes.com/content/123456789",
                tags: ["economy", "politics"],
                likes: 24,
                views: 765,
                comments: 9
            }]
        }
}
