FROM nginx:latest
LABEL maintainer="yue"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN rm /etc/nginx/conf.d/default.conf

COPY site.conf /etc/nginx/conf.d/

COPY . /usr/share/nginx/html/

EXPOSE 80
EXPOSE 443

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

USER nginx

CMD ["nginx", "-g", "daemon off;"]